############ pdf newsletters: ################
st_georges_cathedral_prompt = "At St George's Cathedral, I am expecting a confession timetable as follows: Weekdays: 12-12:20 Saturdays: 10:00 - 11:00 and 17:00-17:50 Sundays: 10:00-10:30 and 12:00-12:30 Check this is correct according to this pdf only. If I am correct, return a json response like so: { \"changed\": \"false\" } If I am incorrect, return a json response like so: { \"changed\": \"true\", \"reason\": \"insert max 4 sentences here explaining the change in confession times. Express yourself in an official, public-announcement way. \" } If there is insufficient information to determine if I am correct or not, return a json response like so: { \"changed\": \"unknown\"} Do not elaborate. Communicate entirely using a json response only."
st_patricks_soho_prompt = "At St Patrick's Soho, I am expecting a confession timetable as follows: Weekdays: 12-12:40 and Saturdays: 17:30 - 17:55 and nothing on Sunday. Check this is correct according to this newsletter only. If I am correct, return a json response like so: { changed: \"false\" } If I am incorrect, return a json response like so: { \"changed\": \"true\", reason: \"insert max 4 sentences here explaining the change in confession times. Express yourself in an official, public-announcement way. \" } If there is insufficient information to determine if I am correct or not, return a json response like so: { \"changed\": \"unknown\"} Do not elaborate. Communicate entirely using a json response only."
st_simon_stock_prompt = "At Our lady of Mount Carmel & St Simon Stock, I am expecting a confession timetable as follows: Weekdays: 17:40-18:00, Saturdays: 11:30 - 12:15 & 17:00-17:50 and nothing on Sunday. Check this is correct according to this newsletter only. If I am correct, return a json response like so: { \"changed\": \"false\" } If I am incorrect, return a json response like so: { \"changed\": \"true\", \"reason\": \"insert max 4 sentences here explaining the change in confession times. Express yourself in an official, public-announcement way.\"} If there is insufficient information to determine if I am correct or not, return a json response like so: {\"changed\": \"unknown\"} Do not elaborate. Communicate entirely using a json response only."
farm_street_prompt = "At Farm Street church, I am expecting a confession timetable as follows: Weekdays: 12-12:55, Saturdays: 11:00 - 12:00 & 17:45-17:55, Sundays: 15 minutes before every Mass. Check this is correct according to this pdf only. If I am correct, return a json response like so: { \"changed\": \"false\" } If I am incorrect, return a json response like so: { \"changed\": \"true\", \"reason\": \"insert max 4 sentences here explaining the change in confession times. Express yourself in an official, public-announcement way.\" } If there is insufficient information to determine if I am correct or not, return a json response like so: { \"changed\": \"unknown\"} Do not elaborate. Communicate entirely using a json response only."
corpus_christi_prompt = "At Corpus Christi church, I am expecting a confession timetable as follows: Monday, Wednesday-Friday: 12:35-13:05 only. Check this is correct according to this pdf only. If I am correct, return a json response like so: { \"changed\": \"false\" } If I am incorrect, return a json response like so: { \"changed\": \"true\", \"reason\": \"insert max 4 sentences here explaining the change in confession times. Express yourself in an official, public-announcement way.\" } If there is insufficient information to determine if I am correct or not, return a json response like so: { \"changed\": \"unknown\"} Do not elaborate. Communicate entirely using a json response only."
st_peter_and_paul_prompt = "At St Peter & Paul church, I am expecting a confession timetable as follows: Mondays 11:30am-12:15pm only. Check this is correct according to this pdf only. If I am correct, return a json response like so: { \"changed\": \"false\" } If I am incorrect, return a json response like so: { \"changed\": \"true\", \"reason\": \"insert max 4 sentences here explaining the change in confession times. Express yourself in an official, public-announcement way.\" } If there is insufficient information to determine if I am correct or not, return a json response like so: { \"changed\": \"unknown\"} Do not elaborate. Communicate entirely using a json response only."
# St Etheldreda Newsletter doesn't normally mention confession times, so default to false
st_etheldreda_prompt = "At St Etheldreda church, I am expecting a confession timetable as follows: Monday to Friday, 1.20pm; and at call. Check this is correct according to this pdf only. If I am correct, return a json response like so: { \"changed\": \"false\" } If I am incorrect, return a json response like so: { \"changed\": \"true\", \"reason\": \"insert max 4 sentences here explaining the change in confession times. Express yourself in an official, public-announcement way.\" } If there is insufficient information to determine if I am correct or not, return a json response like so: { \"changed\": \"false\" } Do not elaborate. Communicate entirely using a json response only."
our_lady_queen_of_heaven_prompt = "At Our Lady Queen of Heaven church, I am expecting a confession timetable as follows: Saturdays 16:15-16:45 only and by appointment. Check this is correct according to this pdf only. If I am correct, return a json response like so: { \"changed\": \"false\" } If I am incorrect, return a json response like so: { \"changed\": \"true\", \"reason\": \"insert max 4 sentences here explaining the change in confession times. Express yourself in an official, public-announcement way.\" } If there is insufficient information to determine if I am correct or not, return a json response like so: { \"changed\": \"unknown\"} Do not elaborate. Communicate entirely using a json response only."
our_lady_of_the_rosary_prompt = "At Our Lady of the Rosary Marylebone, I am expecting a confession timetable as follows: Saturdays 5:15pm - 5:45pm only. Check this is correct according to this pdf only. If I am correct, return a json response like so: { \"changed\": \"false\" } If I am incorrect, return a json response like so: { \"changed\": \"true\", \"reason\": \"insert max 4 sentences here explaining the change in confession times. Express yourself in an official, public-announcement way.\" } If there is insufficient information to determine if I am correct or not, return a json response like so: { \"changed\": \"unknown\"} Do not elaborate. Communicate entirely using a json response only. I am interested in the Marylebone timetable only. Ignore the St John's wood timetable."
holy_apostles_prompt = "At Holy Apostles church Pimlico, I am expecting a confession timetable as follows: Saturday 5-5:30pm only and by arrangement. Check this is correct according to this newsletter only. If I am correct, return a json response like so: { \"changed\": \"false\" } If I am incorrect, return a json response like so: { \"changed\": \"true\", \"reason\": \"insert max 4 sentences here explaining the change in confession times. Express yourself in an official, public-announcement way.\" } If there is insufficient information to determine if I am correct or not, return a json response like so: { \"changed\": \"unknown\"} Do not elaborate. Communicate entirely using a json response only."
st_james_prompt = "At St James church, I am expecting a confession timetable as follows: Weekdays 12pm-1pm, Saturday 4:45-5:30pm. Check this is correct according to this newsletter only. If I am correct, return a json response like so: { \"changed\": \"false\" } If I am incorrect, return a json response like so: { \"changed\": \"true\", \"reason\": \"insert max 4 sentences here explaining the change in confession times. Express yourself in an official, public-announcement way.\" } If there is insufficient information to determine if I am correct or not, return a json response like so: { \"changed\": \"unknown\"} Do not elaborate. Communicate entirely using a json response only."
most_precious_blood_prompt = "At Most Precious Blood church, I am expecting a confession timetable as follows: Tuesday - Friday 12.30-12.55, Saturday 10.00-10.25. Check this is correct according to this newsletter only. If I am correct, return a json response like so: { \"changed\": \"false\" } If I am incorrect, return a json response like so: { \"changed\": \"true\", \"reason\": \"insert max 4 sentences here explaining the change in confession times. Express yourself in an official, public-announcement way.\" } If there is insufficient information to determine if I am correct or not, return a json response like so: { \"changed\": \"unknown\"} Do not elaborate. Communicate entirely using a json response only."

############ html newsletters: ################
st_anselm_and_st_caecilia_prompt = "At St Anselm & St Caecilia church, I am expecting a confession timetable as follows: ONDAY-FRIDAY 5.30pm-5.50pm, SATURDAY 5.00pm – 5.40pm. Check this is correct according to this newsletter only. If I am correct, return a json response like so: { \"changed\": \"false\" } If I am incorrect, return a json response like so: { \"changed\": \"true\", \"reason\": \"insert max 4 sentences here explaining the change in confession times. Express yourself in an official, public-announcement way.\" } If there is insufficient information to determine if I am correct or not, return a json response like so: { \"changed\": \"unknown\"} Do not elaborate. Communicate entirely using a json response only. Here is the newsletter text:"
# Brompton Oratory doesn't normally mention confession times, so default to false
brompton_oratory_prompt = "At Brompton Oratory, I am expecting a confession timetable as follows: Weekdays: 12-12:30 and 17:30-18:00 Saturdays: 10:00 - 12:45 & 15:00-18:00 and 17:00-18:00 Sundays: after each mass. Check this is correct according to this newsletter only. If I am correct, return a json response like so: { \"changed\": \"false\" } If I am incorrect, return a json response like so: { \"changed\": \"true\", \"reason\": \"insert max 4 sentences here explaining the change in confession times. Express yourself in an official, public-announcement way.\" } If there is insufficient information to determine if I am correct or not, return a json response like so: { \"changed\": \"false\" } Do not elaborate. Communicate entirely using a json response only. Here is the newsletter text:"
st_marys_cadogan_street_prompt = "At St Mary's Cadogan Street, I am expecting a confession timetable as follows: Saturday 5.45pm - 6.15pm. Check this is correct according to this newsletter only. If I am correct, return a json response like so: { \"changed\": \"false\" } If I am incorrect, return a json response like so: { \"changed\": \"true\", \"reason\": \"insert max 4 sentences here explaining the change in confession times. Express yourself in an official, public-announcement way.\" } If there is insufficient information to determine if I am correct or not, return a json response like so: { \"changed\": \"unknown\"} Do not elaborate. Communicate entirely using a json response only. Here is the newsletter text:"

############ unique newsletters: ################
westminster_cathedral_prompt = "At Westminster Cathedral, I am expecting a confession timetable as follows: Weekdays: 11:30am-12:30pm and 4:30pm-5:30pm Saturdays: 11:30am - 12:30pm & 5pm-6pm Sundays: 10:30am-12:30pm and 5pm-6:45pm. Check this is correct according to this newsletter schedule only. If I am correct, return a json response like so: { \"changed\": \"false\" } If I am incorrect, return a json response like so: { \"changed\": \"true\", \"reason\": \"insert max 4 sentences here explaining the change in confession times. Express yourself in an official, public-announcement way.\" } If there is insufficient information to determine if I am correct or not, return a json response like so: { \"changed\": \"unknown\"} Do not elaborate. Communicate entirely using a json response only. Here is the weekly newsletter schedule as a html table. In the table body, only read the table row with class \"current-week\". Ignore the other rows:"

############ no up-to-date online newsletter: ################
# Our lady of the assumption, Warwick street
# St Mary Moorfields, Liverpool Street

############ Foreign: ################
# Notre Dame De France, Leicester Square
# Ukrainian Cathedral, Mayfair
